import { test, expect } from "@playwright/test";
import { createDocument } from "../src/core/document";
test("object mode installs modular vegetation without voxels, removes, restores and persists", async ({page}) => {
  const errors: string[] = []; page.on("pageerror",e=>errors.push(e.message));
  await page.goto("/");
  await page.locator("#file").setInputFiles({name:"empty.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(createDocument([],42,"shop")))});
  await page.locator('[data-camera="top"]').click();
  await page.locator("#edit-mode").selectOption("object");
  await page.locator("#object-category").selectOption("vegetation");
  const canvas=page.locator("canvas"), b=(await canvas.boundingBox())!;
  const click=()=>page.mouse.click(b.x+b.width/2+2,b.y+b.height/2+2);
  await click();
  await expect(canvas).toHaveAttribute("data-scene-assets","shrub");
  await expect(page.locator("#stats strong").first()).toHaveText("0");
  await canvas.focus(); await page.keyboard.press("Control+z");
  await expect(canvas).toHaveAttribute("data-scene-assets","");
  await page.keyboard.press("Control+Shift+z");
  await expect(canvas).toHaveAttribute("data-scene-assets","shrub");
  await page.locator("#object-height").fill("3"); await click();
  await expect(canvas).toHaveAttribute("data-scene-assets",/tree-bottom,tree-middle-1,tree-top/);
  const downloadPromise=page.waitForEvent("download"); await page.locator("#save").click();
  const download=await downloadPromise; const path=await download.path();
  await page.locator("#new").click(); await page.locator("#file").setInputFiles(path!);
  await expect(canvas).toHaveAttribute("data-scene-assets",/tree-top/);
  await page.mouse.click(b.x+b.width/2+2,b.y+b.height/2+2,{button:"right"});
  await expect(canvas).toHaveAttribute("data-scene-assets","");
  expect(errors).toEqual([]);
});
