import { expect, it } from "vitest";
import { createDocument, exportDocument, loadDocument, replaceSceneInputs } from "../src/core/document";
import { generateDocument } from "../src/core/generate-document";
import { editObjects } from "../src/scene-editor";
import { DocumentHistory } from "../src/editor";
import { objectContext, type ObjectInput } from "../src/core/scene-inputs";
const ground = { direction: "PY" as const, cells: [[0,-1,0] as [number,number,number]] };
it("adds/removes one layer, regenerates a tree, and preserves volume/history/JSON", () => {
  const doc = createDocument([],42,"shop");
  const first = editObjects(doc,ground,"vegetation","add");
  const second = editObjects(first.document,first.selection,"vegetation","add");
  const third = editObjects(second.document,second.selection,"vegetation","add");
  expect(first.document.grid).toEqual([]);
  expect(generateDocument(first.document).scenePlacements?.map(p=>p.asset)).toEqual(["shrub"]);
  expect(generateDocument(third.document).scenePlacements?.map(p=>p.asset)).toEqual(["tree-bottom","tree-middle","tree-top"]);
  const fourth = editObjects(third.document,third.selection,"vegetation","add");
  const fourthTiles = generateDocument(fourth.document).scenePlacements!;
  expect(fourthTiles.map(p=>p.asset)).toEqual(["tree-bottom","tree-middle","tree-middle","tree-top"]);
  expect(new Set(fourthTiles.map(p=>p.id)).size).toBe(4);
  expect(fourthTiles.map(p=>[p.center[1],p.size[1]])).toEqual([[.5,1],[1.5,1],[2.5,1],[3.5,1]]);
  expect(loadDocument(exportDocument(fourth.document))).toEqual(fourth.document);
  expect(editObjects(fourth.document,fourth.selection,"vegetation","remove").document).toEqual(third.document);
  expect(third.document.sceneInputs?.objects).toHaveLength(1);
  expect(third.selection.cells).toEqual([[0,2,0]]);
  expect(generateDocument(loadDocument(exportDocument(third.document)))).toEqual(generateDocument(third.document));
  const history = new DocumentHistory(first.document); history.commit(third.document);
  expect(history.undo()).toEqual(first.document); expect(history.redo()).toEqual(third.document);
  const cut = editObjects(third.document,third.selection,"vegetation","remove");
  expect(cut.document).toEqual(second.document);
  expect(editObjects(cut.document,cut.selection,"vegetation","add").document).toEqual(third.document);
  const last = editObjects(first.document,first.selection,"vegetation","remove");
  expect(last.document.sceneInputs?.objects).toEqual([]);
  expect(last.selection).toEqual(ground);
  expect(editObjects(last.document,last.selection,"vegetation","add").document).toEqual(first.document);
});
it("preserves supported and unresolved source intentions without invoking the old cell-by-cell fixture path", () => {
  const input: ObjectInput={id:'a',category:'lighting',cells:[[0,0,0]],direction:'PY'};
  expect(objectContext(input,[],[[1,0,0]])).toBe('roadside');
  const groundLight=editObjects(createDocument([]),ground,'lighting','add').document;
  expect(generateDocument(groundLight,{mode:'development-preview'}).environment?.stages.find(s=>s.stage==='fixtures')?.state).toBe('ready');
  const doc=createDocument([[0,0,0]],42,'shop');
  const roof=editObjects(doc,{direction:'PY',cells:[[0,0,0]]},'facility','add').document;
  expect(objectContext(roof.sceneInputs.objects[0],doc.grid,[])).toBe('roof');
  const wall=editObjects(doc,{direction:'PX',cells:[[0,0,0]]},'lighting','add').document;
  expect(objectContext(wall.sceneInputs.objects[0],doc.grid,[])).toBe('wall');
  const unsupported=editObjects(createDocument([]),{direction:'PY',cells:[[2,2,0]]},'vegetation','add').document;
  const result=generateDocument(unsupported);
  expect(unsupported.sceneInputs.objects).toHaveLength(1);expect(result.scenePlacements).toEqual([]);
  expect(result.environment?.spatial?.diagnostics.some(d=>d.code==='UNSUPPORTED_OBJECT_SUPPORT')).toBe(true);
});
it("rejects obsolete misc categories instead of silently migrating them",()=>{
  const doc=editObjects(createDocument([]),ground,'facility','add').document;
  const old=JSON.parse(exportDocument(doc));old.sceneInputs.objects[0].category='misc';expect(()=>loadDocument(JSON.stringify(old))).toThrow();
});

it("edits a multi-cell object's height partially without losing neighboring columns", () => {
  const base = {direction:"PY" as const,cells:[[0,-1,0],[1,-1,0]] as [number,number,number][]};
  const first = editObjects(createDocument([]),base,"facility","add");
  expect(first.document.sceneInputs!.objects[0].cells).toHaveLength(2);
  const raised = editObjects(first.document,{direction:"PY",cells:[[0,0,0]]},"facility","add");
  expect(raised.document.sceneInputs!.objects.flatMap(o=>o.cells)).toEqual([[0,0,0],[0,1,0],[1,0,0]]);
  const lowered = editObjects(raised.document,raised.selection,"facility","remove");
  expect(lowered.document.sceneInputs!.objects.flatMap(o=>o.cells)).toEqual([[0,0,0],[1,0,0]]);
  expect(loadDocument(exportDocument(raised.document))).toEqual(raised.document);
});
it("matches layer bounds, blocks collisions, and keeps failed edits atomic", () => {
  const first=editObjects(createDocument([[0,2,0]]),ground,"facility","add");
  const second=editObjects(first.document,first.selection,"facility","add");
  expect(()=>editObjects(second.document,second.selection,"facility","add")).toThrow(/겹칩니다/);
  expect(editObjects(first.document,ground,"facility","add").changed).toBe(false);
  expect(editObjects(first.document,{direction:"PY",cells:[[2,0,0]]},"facility","remove").changed).toBe(false);
  expect(()=>editObjects(first.document,first.selection,"vegetation","add")).toThrow(/카테고리/);
  let step=editObjects(createDocument([]),ground,"vegetation","add");
  for(let i=1;i<32;i++) step=editObjects(step.document,step.selection,"vegetation","add");
  expect(step.document.sceneInputs!.objects[0].cells).toHaveLength(32);
  expect(()=>editObjects(step.document,step.selection,"vegetation","add")).toThrow(/32/);
});
