import * as ui from './ui';
import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('define once, place twice, and propagate edits while preserving instance positions and links', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await ui.newPreset(page);
  await expect(page.locator('[data-node]')).toHaveCount(4);
  await page.locator('[name=Name]').fill('Armor');
  await page.locator('[name=DisplayName]').fill('머신건 방어력');
  await page.locator('[name=MaxLevel]').fill('4');
  await page.locator('#apply').click();
  await ui.place(page, 'Armor');
  await page.locator('[name=X]').fill('600');
  await page.locator('[name=Y]').fill('96');
  await page.locator('#apply').click();
  await page.locator('#parent-select').selectOption('MachineGunDamage');
  await page.locator('#add-parent').click();
  await ui.place(page, 'Armor');
  await expect(page.locator('[data-node=Armor_2]')).toHaveCount(1);
  await ui.editPreset(page, 'Armor');
  await page.locator('[name=Name]').fill('ArmorShared');
  await page.locator('[name=DisplayName]').fill('강화된 방어력');
  await page.locator('[name=MaxLevel]').fill('8');
  await page.locator('#apply').click();
  await expect(page.locator('[data-node=Armor] .investment-limit')).toHaveText('×8');
  await expect(page.locator('[data-node=Armor_2] .investment-limit')).toHaveText('×8');
  await page.locator('#delete-preset').click();
  await expect(page.locator('#settings-message')).toContainText('배치 중');
  await ui.selectNode(page, 'Armor');
  await expect(page.locator('[name=X]')).toHaveValue('600');
  await expect(page.locator('[name=Y]')).toHaveValue('96');
  await expect(page.locator('[name=MaxLevel]')).toHaveCount(0);
  await expect(page.locator('.edge[data-from=MachineGunDamage][data-to=Armor]')).toHaveCount(1);
  await ui.exportProject(page);
  const rows = JSON.parse(await page.locator('#json-preview').innerText());
  expect(rows.filter((row: { SkillId: string }) => row.SkillId === 'ArmorShared')).toHaveLength(2);
  expect(rows.find((row: { Name: string }) => row.Name === 'Armor')).toMatchObject({ MaxLevel: 8, X: 600, Y: 96, Prerequisites: ['MachineGunDamage'] });
  await page.locator('#close-export').click();
  await page.reload();
  await expect(page.locator('[data-preset-id=ArmorShared]')).toHaveCount(1);
  await expect(page.locator('[data-node=Armor_2] .investment-limit')).toHaveText('×8');
  expect(errors).toEqual([]);
});

test('drag a definition onto canvas; unused definitions survive save/reopen and empty trees', async ({ page }) => {
  await page.goto('/');
  await page.locator('[data-preset-id=MachineGunRange]').dragTo(page.locator('#canvas'), { targetPosition: { x: 100, y: 110 } });
  await expect(page.locator('[data-node=MachineGunRange_2]')).toHaveCount(1);
  await ui.newPreset(page);
  await page.locator('[name=Name]').fill('Unused');
  await page.locator('[name=DisplayName]').fill('미배치 스킬');
  await page.locator('#apply').click();
  const downloadPromise = page.waitForEvent('download');
  await ui.saveProject(page);
  const download = await downloadPromise;
  const data = await readFile((await download.path())!, 'utf8');
  expect(JSON.parse(data).presets).toHaveLength(5);
  await ui.fileAction(page, 'new');
  await expect(page.locator('[data-node]')).toHaveCount(0);
  await expect(page.locator('[data-preset-id=Unused]')).toHaveCount(1);
  await page.locator('#file').setInputFiles({ name: 'presets.skilltree.json', mimeType: 'application/json', buffer: Buffer.from(data) });
  await expect(page.locator('[data-node]')).toHaveCount(5);
  await expect(page.locator('[data-preset-id=Unused]')).toHaveCount(1);
  await ui.editPreset(page, 'Unused');
  await page.locator('#delete-preset').click();
  await expect(page.locator('[data-preset-id=Unused]')).toHaveCount(0);
  await ui.undo(page);
  await expect(page.locator('[data-preset-id=Unused]')).toHaveCount(1);
  await page.screenshot({ path: 'artifacts/skill-presets.png' });
});
