import * as ui from './ui';
import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('add and rename an effect target in the UI, update its references and save/reopen the catalog', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await ui.editPreset(page, 'MachineGunDamage');
  await page.getByRole('button', { name: '대상 관리', exact: true }).click();
  await page.getByRole('textbox', { name: '새 효과 태그', exact: true }).fill('MachineGun.ReloadSpeed');
  await page.getByRole('button', { name: '대상 추가', exact: true }).click();
  const row = page.locator('.target-row').filter({ has: page.getByRole('textbox', { name: 'MachineGun.ReloadSpeed 태그 ID', exact: true }) });
  let id = (await row.getAttribute('data-target-row'))!;
  expect(id).toBe('MachineGun.ReloadSpeed');
  await page.locator('#settings-presets').click();
  await page.getByRole('combobox', { name: '효과 대상', exact: true }).selectOption({ label: 'MachineGun.ReloadSpeed' });
  await page.locator('#apply').click();
  await page.locator('#edit-targets').click();
  const used = page.locator(`[data-target-row="${id}"]`);
  await expect(used.getByRole('button', { name: '삭제', exact: true })).toBeDisabled();
  await used.locator('input').fill('MachineGun.ReloadEfficiency');
  await used.getByRole('button', { name: '태그 적용', exact: true }).click();
  id = 'MachineGun.ReloadEfficiency';
  await expect(page.locator(`[data-target-row="${id}"] input`)).toHaveValue('MachineGun.ReloadEfficiency');
  await page.screenshot({ path: 'artifacts/effect-target-manager.png' });
  await page.locator('#settings-presets').click();
  await expect(page.locator('[name=StatId]')).toHaveValue(id);
  await expect(page.locator('[name=StatId] option:checked')).toHaveText('MachineGun.ReloadEfficiency');
  await ui.exportProject(page);
  expect(JSON.parse(await page.locator('#json-preview').innerText())[0].StatId).toBe(id);
  await page.locator('#close-export').click();
  const waiting = page.waitForEvent('download'); await ui.saveProject(page);
  const data = await readFile((await (await waiting).path())!, 'utf8');
  expect(JSON.parse(data).effectTargets).toContainEqual({ id });
  await ui.fileAction(page, 'new');
  await ui.targets(page);
  await expect(page.locator(`[data-target-row="${id}"]`)).toBeVisible();
  await page.locator('#settings-presets').click();
  await page.locator('#file').setInputFiles({ name: 'catalog.skilltree.json', mimeType: 'application/json', buffer: Buffer.from(data) });
  await page.reload();
  await ui.editPreset(page, 'MachineGunDamage');
  await expect(page.locator('[name=StatId]')).toHaveValue(id);
  await expect(page.locator('[name=StatId] option:checked')).toHaveText('MachineGun.ReloadEfficiency');
  expect(errors).toEqual([]);
});

test('invalid tags are rejected, unused targets can be deleted and deletion can be undone', async ({ page }) => {
  await page.goto('/');
  await ui.targets(page);
  await page.locator('#new-target-tag').fill('machinegun.damage');
  await page.getByRole('button', { name: '대상 추가', exact: true }).click();
  await expect(page.locator('#target-message')).toContainText('중복');
  await expect(page.locator('.target-row')).toHaveCount(4);
  await page.locator('#new-target-tag').fill('  ');
  await page.getByRole('button', { name: '대상 추가', exact: true }).click();
  await expect(page.locator('#target-message')).toContainText('1~128자');
  await page.locator('#new-target-tag').fill('MachineGun.Unused');
  await page.getByRole('button', { name: '대상 추가', exact: true }).click();
  const row = page.locator('.target-row').filter({ has: page.getByRole('textbox', { name: 'MachineGun.Unused 태그 ID', exact: true }) });
  let id = (await row.getAttribute('data-target-row'))!;
  await row.getByRole('button', { name: '삭제', exact: true }).click();
  await expect(page.locator(`[data-target-row="${id}"]`)).toHaveCount(0);
  await page.locator('#settings-presets').click();
  await ui.undo(page);
  await ui.targets(page);
  await expect(page.locator(`[data-target-row="${id}"]`)).toHaveCount(1);
});
